### ISSUE TITLE
How to enable PMU counters on multi cpus

### ISSUE THREAD

**Issue by monellz** [jerinjacobk/armv8_pmu_cycle_counter_el0#3]
Hello,
I've been testing PMU on a real board which has 8 cpus, and this repo helps me a lot and work perfectly on a single cpu(I disabled other cpus).

However, it always gives me "Illegal Instruction" when I try to read pmccntr_el0 when all cpus are on.

Is there any idea why it cannot work on multi cpus environment?

**Comment by jerinjacobk** [comment]
It should work. As on init(), it is enabling on all the ONLINE cpus.
